# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    # Run every day at 02:00
    - cron: '0 2 * * 0-6'

jobs:
  archlinux_gcc_release:
    name: Archlinux [GCC|Release]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      env:
        COMPILER: gcc
        DOCKERFILE: Dockerfile.archlinux
        BUILD_TYPE: Release
      run: |
        docker build -t "${DOCKERFILE,,}" -f ".ci/docker/$DOCKERFILE" .;
        docker run -itd -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE --env-file ./.ci/docker/env.list --name dart-docker "${DOCKERFILE,,}";
    - name: Build
      run: |
        docker exec dart-docker /bin/sh -c "cd $GITHUB_WORKSPACE && ./.ci/script_archlinux.sh";
